### ISSUE TITLE
Confused about v 7.3

### ISSUE THREAD

**Issue by Korporal** [dotnet/csharplang#1516]
The latest VS release notes mention  that C# 7.3 has some new features, among then [this one](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/pattern-based-fixed.md). However that pages states that the feature is just a proposal and not implemented, why the contradiction? Other apparently implemented features are similarly described as not yet implemented, surely it isn't hard to update these feature request pages once something is _officially_ released?

**Comment by jcouv** [comment]
That was an oversight. Fixed.
Here's the list of [C# 7.3 features](https://github.com/dotnet/csharplang/blob/master/Language-Version-History.md#c-73-visual-studio-2017-version-157) that shipped.

**Comment by JesperTreetop** [comment]
There are several other features linked in that section (`unmanaged` constraints, stackalloc initializers, expression variables in initializers) where the proposal has not been updated, some not even to show that a prototype has been started. Forgetting to mark that the feature is shipped is one thing, but at this point we don't even know if the feature still works as described in the document, what the answers to any unresolved questions in the proposal are, etc.

Maybe it's worth revisiting how the current process works - it doesn't quite seem to keep pace with the actual development.

**Comment by jcouv** [comment]
I agree. I don't think those checkboxes should be in those documents in the first place. They should be in the [championed issues](https://github.com/dotnet/csharplang/issues?q=is%3Aopen+is%3Aissue+milestone%3A7.3).
I'll do a scrub.

**Comment by jcouv** [comment]
Should be fixed now.

@JesperTreetop As a side note, the document that we refresh the most promptly with implementation status is the [language feature status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md).

Thanks for raising the issue.

**Comment by Korporal** [comment]
@jcouv - Much appreciated!

**Comment by JesperTreetop** [comment]
Thanks, and noted. I think it's still unclear whether the proposals are intended as living proposals or just snapshots from early stages in development. I still don't know exactly how some features in C# 7.3 work because there are no official docs despite it being out and supported for a week now. I don't know what "strongname" in the feature status document refers to at all. I understand the disclaimer on that page about "active development", but this thing has *shipped* now, and been in preview for months.

I appreciate the transformation of C# over the past few years, the openness, the renewed willingness to put features in there that may be niche but that will help or sand down sharp corners, and I definitely both respect the development effort and like the documentation produced for [What's new in C# 7.2](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-2) (for example). I also understand that a ton of the actual work happens in code changes and in the issues for each proposal and that things can get out of sync when deadlines loom and bugs happen. So with all that said, of course I feel a bit like an ass for talking about this - but as a user of C# who's interested in the language's evolution, who appreciates clarity and documentation, it's nevertheless frustrating when I want to read up on new features and there's no clear way to do so, so I wanted to voice my concern in this issue. Hopefully this can be addressed over time.

**Comment by jcouv** [comment]
@JesperTreetop We intend to update the proposals to reflect the features as implemented. That said, there is some variability.

In terms of status for implementation, the most reliable source is the [compiler feature status](https://github.com/dotnet/roslyn/blob/master/docs/Language%20Feature%20Status.md) page. It shows that strongname is done. That feature is that strong name signing (which is an old feature) didn't work on every platform on CoreCLR, but it should now work (see [details](https://github.com/dotnet/docs/issues/3242)).

Lastly, C# 7.3 has only been released for a week. Docs are being worked on as we speak, and will be available on docs.microsoft.com. You can see the PRs on the [docs](https://github.com/dotnet/docs/pull/5408) repo. Feel free to file issues there if something is missing.

**Comment by jcouv** [comment]
@JesperTreetop More progress on [docs for 7.3](https://github.com/dotnet/docs/pull/5448). I expect those will be published in a few days.

**Comment by JesperTreetop** [comment]
@jcouv That's great! Looking forward to reading it. Thanks for putting up with my whining; I appreciate everyone's work on C#, .NET, the compilers, the CLR and so on, and the recent advances are making my life easier every day.

**Comment by jcouv** [comment]
I think the issue was addressed. I'll go ahead and close. 
Feel free to ping if I missed something. Thanks
